title: Cobalt Jekyll Theme
author: xtrp
email: someone@example.com
description: >
  A simple, minimalistic Jekyll theme.

# social links
email_link: "mailto:someone@example.com"
github_link: "https://github.com/xtrp"
stackoverflow_link: "https://stackoverflow.com/users/10007107/fred-adams"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
