title: Cobalt Jekyll Theme
author: Fred Adams
email: someone@example.com
description: >
  A simple, minimalistic Jekyll theme.

# social links
email_link: "mailto:someone@example.com"
github_link: "https://github.com/xtrp/cobalt-jekyll-theme"
stackoverflow_link: "https://stackoverflow.com"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
